# Generated by Django 5.2.7 on 2025-11-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='edges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
