# Generated by Django 5.2.7 on 2025-11-02 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add2Int',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_x', models.FloatField(default=0.0, help_text='X position in canvas')),
                ('position_y', models.FloatField(default=0.0, help_text='Y position in canvas')),
                ('sum', models.IntegerField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add2int_nodes', to='project.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Integer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_x', models.FloatField(default=0.0, help_text='X position in canvas')),
                ('position_y', models.FloatField(default=0.0, help_text='Y position in canvas')),
                ('number', models.IntegerField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer_nodes', to='project.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_x', models.FloatField(default=0.0, help_text='X position in canvas')),
                ('position_y', models.FloatField(default=0.0, help_text='Y position in canvas')),
                ('text', models.TextField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_nodes', to='project.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
