# Generated by Django 5.2.7 on 2025-11-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_accuracy_dataset_featureselection_linearregression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add2int',
            name='sum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
