# Generated by Django 5.2.7 on 2025-11-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_alter_add2int_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
