# Generated by Django 5.2.7 on 2025-11-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_alter_text_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add2int',
            name='sum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
